import java.util.*;
public class NUMBERGUESSING_T2 
{
 public static void main(String[] args) 
 {
    Scanner sc=new Scanner(System.in);
    int chances=7;
    int total=0;
    int number = 1+(int)(100* Math.random());
    int K = 1;
    System.out.println("RULES FOR PLAYING THE NUMBER GUSSING GAME");
    System.out.println("-------------------------------------------------------");
    System.out.println("SYSTEM WILL GENERATE A RANDOM NUMBER BETWEEN 1 TO 100!!");
    System.out.println("YOU HAVE 7 CHANCES TO GUESS IT CORRECTLY");
    System.out.println("THE GAME ENDS WHEN YOU HAVE NO CHANCES LEFT!!");
    while (chances > 0){
        if(K ==1 )
        {
        System.out.println("");
        System.out.println("RANDOM NUMBER IS GENERATED BY SYSTEM,TRY TO GUESS IT!!...\nALL THE BEST");
        K = 0;
        }
    System.out.print("\nENTER THE GUESS:");
    int num=sc.nextInt();
        if(num>100 || num <= 0)
        {
        System.out.println("INVALID NUMBER!!");
        System.out.println("PLEASE ENTER NUMBER WITHIN GIVEN RANGE");
        }
        else if(num==number)
        {
            System.out.println("BRAVOO!! YOU GUESSED IT RIGHT...");
            total+=50;
            System.out.println("YOUR CURRENT TOTAL IS : "+total);
            number=(int)(Math.random()*100);
            chances=7;
            K = 1;
        }
        else if(num<number)
        {
            System.out.println("YOUR NUMBER IS SMALLER THAN SYSTEM GENERATED NUMBER \nTRY ANOTHER NUMBER");
            if (chances-1 > 0) 
            {
                    System.out.println("CHANCES LEFT: " +(chances-1));    
            }   
            chances--;
        }
        else
        {
            System.out.println("YOUR NUMBER IS GREATER THAN SYSTEM GENERATED NUMBER \nTRY ANOTHER NUMBER");
            if (chances-1 > 0) 
            {
                System.out.println("CHANCES LEFT: " +(chances-1));    
            }
            chances--;
        }
    }
        System.out.println("");
        System.out.println("OPPS! NO CHANCES LEFT...\nPLAY AGAIN TO BEAT YOUR OWN SCORE...");
        System.out.println("\nTHE SYSTEM GENERATED NUMBER IS:"+number);
        System.out.println("\nYOUR TOTAL SCORE IS : "+total+" POINTS");
        sc.close();
 }
}